spring.application.name=journalApp

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb
#spring.data.mongodb.username=username
#spring.data.mongodb.password=password
spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.security=TRACE
#spring.security.user.name=shubham
#spring.security.user.password=1234

#production port
server.port=8081